/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/gwDxTmFubHo
 */
import { Label } from "../ui/label"
import { Input } from "../ui/input"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "../ui/select"
import { Button } from "../ui/button"

export function deploy_token2() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen py-8 bg-gray-100 dark:bg-gray-800">
      <section className="container mx-auto">
        <div className="grid grid-cols-1 gap-8 md:grid-cols-2">
          <div className="flex flex-col justify-center space-y-4">
            <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl text-center">
              Deploy Your ERC20 Token in Style
            </h1>
            <p className="text-center text-gray-500">
              Welcome to the future of token deployment. Get ready for an unparalleled experience.
            </p>
            <div className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="token-name">Token Name</Label>
                <Input id="token-name" onChange={undefined} placeholder="MyToken" required value={undefined} />
              </div>
              <div className="space-y-2">
                <Label htmlFor="supply">Total Supply</Label>
                <Input id="supply" onChange={undefined} placeholder="1000000" required value={undefined} />
              </div>
              <div className="space-y-2">
                <Label htmlFor="network">Network</Label>
                <Select>
                  <SelectTrigger>
                    <SelectValue>Ethereum</SelectValue>
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="ethereum">Ethereum</SelectItem>
                    <SelectItem value="bsc">Binance Smart Chain</SelectItem>
                    <SelectItem value="polygon">Polygon</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <Button className="w-full bg-gradient-to-r from-yellow-400 to-red-500" onClick={undefined}>
                Deploy Your Token in Style
              </Button>
            </div>
          </div>
          <div className="hidden md:flex items-center justify-center">
            <img
              alt="Deploy Token Image"
              className="object-cover rounded-lg shadow-2xl"
              height={500}
              src="/placeholder.svg"
              style={{
                aspectRatio: "500/500",
                objectFit: "cover",
              }}
              width={500}
            />
          </div>
        </div>
      </section>
    </div>
  )
}
